version = 0.1
[default.deploy.parameters]
stack_name = "key-managment-service"
resolve_s3 = true
s3_prefix = "key-managment-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DomainName=\"corrections-dev.tylermobileapps.com\" CORSOrigin=\"*\" HostedZoneId=\"Z0400568NBE46SDQ3ZZN\""
image_repositories = []
